trigger:
- azure-pipelines

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: dockerhub.com/alleeclark/git2consul
  dockerHub: git2consul

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: $(dockerHub)
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: '$(Build.SourcesDirectory)/docker/Dockerfile'
        buildContext: $(Build.SourcesDirectory)
        tags: |
          $(tag)