trigger:
- azure-pipelines

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: dockerhub.com/alleeclark/git2consul
  dockerHub: 'git2consul'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: $(imageName)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
  - job: Push
    displayName: Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: Push image
        inputs:
          containerRegistry: |
            $(dockerHub)
          repository: $(imageName):$(tag)
          command: push
          tags: |
            $(tag)