git-user = "d-git2consul"
git-url = "https://github.com/alleeclark/test-git2consul.git"
git-branch = "facts"
git-dir = "/var/git2consul/data"
git-ssh-publickey-path = ""
git-ssh-privatekey-path = ""
git-ssh-passphrase-path = ""
git-remote = "origin"
consul-addr = "localhost:8500"
consul-path = "git2consul3"
metrics = false
pushgateway-addr = ""
log-level = "debug"
log-format = "text"